### ISSUE TITLE
Not creating splash image for ios after I've modified LaunchScreen.storyboard previously

### ISSUE THREAD

**Issue by jmdibble** [jonbhanson/flutter_native_splash#139]
Creating splash image doesn't work for ios as I've edited my LaunchScreen.storyboard previously in Xcode. It does work for Android though.

Run:
`flutter pub run flutter_native_splash:create`

Output:
```
[Android] Creating splash images
[Android] Updating android/app/src/main/res/drawable/launch_background.xml with splash image path
[Android] Updating android/app/src/main/res/values/colors.xml with color for splash screen background
[Android] Updating styles.xml with full screen mode setting
[iOS] Creating splash images
[iOS] Updating LaunchScreen.storyboard with width, and height
Unhandled exception:
*** ERROR [flutter_native_splash] ***
LaunchScreenStoryboardModified
Not able to find 'LaunchImage' in LaunchScreen.storyboard. Image for splash screen not updated. Did you modify your default LaunchScreen.storyboard file?
#0      _updateLaunchScreenStoryboard.<anonymous closure> (package:flutter_native_splash/ios.dart:142:21)
#1      Iterable.firstWhere (dart:core/iterable.dart:577:38)
#2      _updateLaunchScreenStoryboard (package:flutter_native_splash/ios.dart:139:63)
#3      _applyLaunchScreenStoryboard (package:flutter_native_splash/ios.dart:107:12)
#4      _createiOSSplash (package:flutter_native_splash/ios.dart:66:9)
<asynchronous suspension>
#5      tryCreateSplashByConfig (package:flutter_native_splash/supported_platform.dart:61:11)
<asynchronous suspension>
#6      tryCreateSplash (package:flutter_native_splash/supported_platform.dart:27:9)
<asynchronous suspension>
#7      createSplash (package:flutter_native_splash/flutter_native_splash.dart:17:9)
#8      main (file:///Users/josh/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-0.3.2/bin/create.dart:5:3)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

**Flutter doctor**

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.5 19F101, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Connected device (1 available)
```

**Comment by jmdibble** [comment]
Thanks! I think I might have messed it up in the past by messing with the launchscreen in Xcode without really knowing what I was doing. 

This is my LaunchScreen.storyboard

```
<?xml version="1.0" encoding="UTF-8"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="17701" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" launchScreen="YES" colorMatched="YES" initialViewController="01J-lp-oVM">
    <device id="retina6_1" orientation="portrait" appearance="light"/>
    <dependencies>
        <deployment identifier="iOS"/>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="17703"/>
        <capability name="System colors in document resources" minToolsVersion="11.0"/>
        <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>
    </dependencies>
    <scenes>
        <!--View Controller-->
        <scene sceneID="EHf-IW-A2E">
            <objects>
                <viewController id="01J-lp-oVM" sceneMemberID="viewController">
                    <layoutGuides>
                        <viewControllerLayoutGuide type="top" id="Ydg-fD-yQy"/>
                        <viewControllerLayoutGuide type="bottom" id="xbc-2k-c8Z"/>
                    </layoutGuides>
                    <view key="view" contentMode="scaleToFill" id="Ze5-6b-2t3">
                        <rect key="frame" x="0.0" y="0.0" width="414" height="896"/>
                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                        <subviews>
                            <imageView opaque="NO" clipsSubviews="YES" multipleTouchEnabled="YES" contentMode="scaleAspectFill" misplaced="YES" image="bg" translatesAutoresizingMaskIntoConstraints="NO" id="YRO-k0-Ey4">
                                <rect key="frame" x="-1.2366863905326682" y="0.0" width="413.99999999999989" height="895.99999999999989"/>
                                <color key="tintColor" systemColor="opaqueSeparatorColor"/>
                                <preferredSymbolConfiguration key="preferredSymbolConfiguration" scale="default"/>
                            </imageView>
                            <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="251" verticalHuggingPriority="251" fixedFrame="YES" image="fg" translatesAutoresizingMaskIntoConstraints="NO" id="Oij-XR-SAQ">
                                <rect key="frame" x="-1.2366863905326682" y="300" width="413.99999999999989" height="295.99999999999989"/>
                                <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMaxY="YES"/>
                            </imageView>
                        </subviews>
                        <color key="backgroundColor" red="1" green="1" blue="1" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>
                        <constraints>
                            <constraint firstItem="YRO-k0-Ey4" firstAttribute="centerX" secondItem="Ze5-6b-2t3" secondAttribute="centerX" id="1a2-6s-vTC"/>
                            <constraint firstItem="YRO-k0-Ey4" firstAttribute="centerY" secondItem="Ze5-6b-2t3" secondAttribute="centerY" id="4X2-HB-R7a"/>
                        </constraints>
                    </view>
                </viewController>
                <placeholder placeholderIdentifier="IBFirstResponder" id="iYj-Kq-Ea1" userLabel="First Responder" sceneMemberID="firstResponder"/>
            </objects>
            <point key="canvasLocation" x="76.811594202898561" y="251.11607142857142"/>
        </scene>
    </scenes>
    <resources>
        <image name="bg" width="2048" height="2732"/>
        <image name="fg" width="2048" height="2732"/>
        <systemColor name="opaqueSeparatorColor">
            <color red="0.77647058823529413" green="0.77647058823529413" blue="0.78431372549019607" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>
        </systemColor>
    </resources>
</document>
```

And here is my file structure if that helps to see namings:

![Screenshot 2021-03-09 at 14 00 16](https://user-images.githubusercontent.com/32303700/110481771-d4bab400-80df-11eb-8958-419c1a49e772.png)

**Comment by jonbhanson** [comment]
@jmdibble a quick way too see how your file has been changed is to compare your LaunchScreen.storyboard with the one that is included with a new Flutter project.  Here is that default LaunchScreen.storyboard:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="12121" systemVersion="16G29" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" launchScreen="YES" colorMatched="YES" initialViewController="01J-lp-oVM">
    <dependencies>
        <deployment identifier="iOS"/>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="12089"/>
    </dependencies>
    <scenes>
        <!--View Controller-->
        <scene sceneID="EHf-IW-A2E">
            <objects>
                <viewController id="01J-lp-oVM" sceneMemberID="viewController">
                    <layoutGuides>
                        <viewControllerLayoutGuide type="top" id="Ydg-fD-yQy"/>
                        <viewControllerLayoutGuide type="bottom" id="xbc-2k-c8Z"/>
                    </layoutGuides>
                    <view key="view" contentMode="scaleToFill" id="Ze5-6b-2t3">
                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                        <subviews>
                            <imageView opaque="NO" clipsSubviews="YES" multipleTouchEnabled="YES" contentMode="center" image="LaunchImage" translatesAutoresizingMaskIntoConstraints="NO" id="YRO-k0-Ey4">
                            </imageView>
                        </subviews>
                        <color key="backgroundColor" red="1" green="1" blue="1" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>
                        <constraints>
                            <constraint firstItem="YRO-k0-Ey4" firstAttribute="centerX" secondItem="Ze5-6b-2t3" secondAttribute="centerX" id="1a2-6s-vTC"/>
                            <constraint firstItem="YRO-k0-Ey4" firstAttribute="centerY" secondItem="Ze5-6b-2t3" secondAttribute="centerY" id="4X2-HB-R7a"/>
                        </constraints>
                    </view>
                </viewController>
                <placeholder placeholderIdentifier="IBFirstResponder" id="iYj-Kq-Ea1" userLabel="First Responder" sceneMemberID="firstResponder"/>
            </objects>
            <point key="canvasLocation" x="53" y="375"/>
        </scene>
    </scenes>
    <resources>
        <image name="LaunchImage" width="168" height="185"/>
    </resources>
</document>
```

Based on this comparison, it looks like you have renamed your `LaunchImage` to `fg`.  If you rename `fg` back to `LaunchImage`, it should fix the problem.  It is worth noting that the plugin creates a background color by adding a full screen image called `LaunchBackground` with the desired color.  With this in mind, you should probably rename your `bg` to `LaunchBackground`.

**Comment by jmdibble** [comment]
Sorted! 

You're correct. I removed the fg.imageset and bg.imageset folders, reset my LaunchScreen.storyboard to the one you pasted above and then re-ran `create` and it generated the launch screen as expected. 

Thanks for your help
