### ISSUE TITLE
[android] error: 'cover' is incompatible with attribute gravity (attr)

### ISSUE THREAD

**Issue by aoatmon** [jonbhanson/flutter_native_splash#234]
```yaml
environment:
  sdk: '>=2.14.4 <3.0.0'
  flutter: ^2.5.3

dev_dependencies:
  flutter_native_splash: ^1.3.1
  
flutter_native_splash:
  color: '#000000'
  image: images/splash.png
  android: true
  ios: true
  android_gravity: cover
  ios_content_mode: cover


flutter:
  generate: true
  uses-material-design: true
```
```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-EE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.1)
[✓] Connected device (3 available)

• No issues found!
```
```console
╰─$ flutter pub run flutter_native_splash:create                                                                                                                                                                                          1 ↵
[Android] Creating splash images
[Android] Updating launch background(s) with splash image path...
[Android]    - android/app/src/main/res/drawable/launch_background.xml
[Android]    - android/app/src/main/res/drawable-v21/launch_background.xml
[Android] Updating styles...
[Android]    - android/app/src/main/res/values/styles.xml
[iOS] Creating splash images
[iOS] Updating LaunchScreen.storyboard with width, and height
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
Web folder not found, skipping web splash update...

Native splash complete. 👍
Now go finish building something awesome! 💪 You rock! 🤘🤩
```

```console
[        ] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Execution failed for task ':app:processDebugResources'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > Android resource linking failed
[        ]      /Users/francesco/development/<my-app>/android/app/src/main/res/drawable/launch_background.xml:7: AAPT: error: 'cover' is incompatible with attribute gravity (attr) flags [bottom=80, center=17, center_horizontal=1,
center_vertical=16, clip_horizontal=8, clip_vertical=128, end=8388613, fill=119, fill_horizontal=7, fill_vertical=112, left=3, right=5, start=8388611, top=48].
[        ]      /Users/francesco/development/<my-app>/android/app/src/main/res/drawable-v21/launch_background.xml:7: AAPT: error: 'cover' is incompatible with attribute gravity (attr) flags [bottom=80, center=17, center_horizontal=1,
center_vertical=16, clip_horizontal=8, clip_vertical=128, end=8388613, fill=119, fill_horizontal=7, fill_vertical=112, left=3, right=5, start=8388611, top=48].
[   +2 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 8s
[ +375 ms] Running Gradle task 'assembleDebug'... (completed in 9.7s)
[   +5 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 14,709ms.
[   +6 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
```

[logs.txt](https://github.com/jonbhanson/flutter_native_splash/files/7526057/logs.txt)

**Comment by jonbhanson** [comment]
android_gravity can be one of the following Android Gravity (see [Gravity](https://developer.android.com/reference/android/view/Gravity)): bottom, center, center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal, fill_vertical, left, right, start, or top.

Cover is not a valid Android Gravity.
