### ISSUE TITLE
Error: Not found: 'dart:js' Error after updated 2.0.3+1

### ISSUE THREAD

**Issue by SpookyJelly** [jonbhanson/flutter_native_splash#292]
**Describe the bug**

Hi, I just having same problem with #286

and thanks to your quick resolution, I also tried brand-new version.

I don't fixed anything but version upgrade. however, my terminal splits a tons of error.

```Error output from Xcode build:
↳
    objc[12968]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x2196dab90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1080ac2c8). One of the two will be used. Which one is undefined.
    objc[12968]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x2196dabe0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1080ac318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **


Xcode's output:
↳
    ../../../flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.3/lib/js.dart:8:1: Error: Not found: 'dart:js'
    export 'dart:js' show allowInterop, allowInteropCaptureThis;
    ^
    Unhandled exception:
    FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs; message=StandardFileSystem only supports file:* and data:* URIs)
    #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
    #1      asFileUri (package:vm/kernel_front_end.dart:614:37)
    #2      writeDepfile (package:vm/kernel_front_end.dart:754:21)
    <asynchronous suspension>
    #3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:571:9)
    <asynchronous suspension>
    #4      starter (package:flutter_frontend_server/server.dart:85:12)
    <asynchronous suspension>
    #5      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
    <asynchronous suspension>
    Failed to package /Users/user/Documents/GitHub/toyproject-flutter.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro Max.
```

when I downgrade previous version (2.0.2) this error disappears and app runs very well

so I think It has a kind of error with dart:js.

could you give me some advice?? It would be really helpful. Thanks.

**Comment by mciekurs2** [comment]
I'm having the same error. Right now, I just generated assets for splash screens and then commented out the plugin.

**Comment by Carapacik** [comment]
Same

**Comment by DerSIlent** [comment]
Been having this issue since yesterday

**Comment by jonbhanson** [comment]
I will push an update to resolve this shortly.
