### ISSUE TITLE
Exception when trying to remove splash screen

### ISSUE THREAD

**Issue by chrisdrobison** [jonbhanson/flutter_native_splash#355]
**Describe the bug**
Exception when attempting to remove splash screen:

```
Restoring Flutter's default native splash screen...
Unhandled exception:
LateInitializationError: Field '_flavorHelper@20018413' has not been initialized.
#0      _flavorHelper (package:flutter_native_splash/cli_commands.dart)
#1      getConfig (package:flutter_native_splash/cli_commands.dart:246:14)
#2      removeSplash (package:flutter_native_splash/cli_commands.dart:184:18)
#3      main.<anonymous closure> (file:///Users/chris/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.2.0+1/bin/remove.dart:6:49)
#4      Parser.parse.<anonymous closure> (package:args/src/parser.dart:106:15)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#6      MapView.forEach (dart:collection/maps.dart:342:10)
#7      Parser.parse (package:args/src/parser.dart:95:22)
#8      ArgParser.parse (package:args/src/arg_parser.dart:334:42)
#9      main (file:///Users/chris/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.2.0+1/bin/remove.dart:7:10)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
```

**To Reproduce**
1. Run `flutter pub run flutter_native_splash:remove`

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] VS Code (version 1.67.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
chris@Chriss-Mac-mini-6 tap_mobile % ./flutterw doctor -v 
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
    • Flutter version 3.0.0 at /Users/chris/dev/tap_mobile/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (8 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/chris/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • F4A93107-0A85-450B-919C-71F4DBCF4EBE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by byounggil** [comment]
same issue here

**Comment by johanneskopf** [comment]
@chrisdrobison @byounggil  I fixed this temporarily by adding
`_flavorHelper = _FlavorHelper(null);`
in line 185 of cli_commands.dart.

As _FlavorHelper gets late-initialized, it has to be assigned once. This is done in the createSplash() method, but not in the removeSplash() method. The above code fixes this issue.

**Comment by jbryanh** [comment]
Update to this October 2023:  move to line 184 like below.
 
file found here: /Users/[YOU]/.pub-cache/hosted/pub.dev/flutter_native_splash-2.2.0+1/lib/cli_commands.dart

void removeSplash({String? path}) {
  print("Restoring Flutter's default native splash screen...");
  _flavorHelper = _FlavorHelper(null);
  final config = getConfig(configFile: path);

**Comment by jonbhanson** [comment]
@jbryanh I believe this should be addressed in the current version.  It looks like you are using an outdated version of the package.  There have been many changes since version 2.2.0.
