### ISSUE TITLE
Getting error 255 on "flutter pub run flutter_native_splash:create"

### ISSUE THREAD

**Issue by DigvijayZ** [jonbhanson/flutter_native_splash#489]
First i triied to remove this splash screen but it was not possible to remove it so I tried to re install it and now after "flutter pub run flutter_native_splash:create" i am getting the following errors :

[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
Unhandled exception:
XmlParserException: ">" expected at 15:3
#0      XmlEventIterator.moveNext (package:xml/src/xml_events/iterator.dart:42:9)
#1      Iterable.forEach (dart:core/iterable.dart:325:23)
#2      XmlNodeDecoder.convertIterable (package:xml/src/xml_events/converters/node_decoder.dart:53:12)
#3      new XmlDocument.parse (package:xml/src/xml/nodes/document.dart:34:41)
#4      _updateInfoPlistFile (package:flutter_native_splash/ios.dart:496:35)
#5      _applyInfoPList (package:flutter_native_splash/ios.dart:485:5)
#6      _createiOSSplash (package:flutter_native_splash/ios.dart:167:3)
#7      createSplashByConfig (package:flutter_native_splash/cli_commands.dart:183:7)
#8      createSplash (package:flutter_native_splash/cli_commands.dart:41:3)
#9      main (file:///C:/Users/Diguj/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.2.16/bin/create.dart:12:3)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255

Can you help in anyway?

**Comment by jonbhanson** [comment]
It looks like you have an error in your Info.plist file.  The XML parser is indicating that there is some invalid XML in there.

**Comment by jonbhanson** [comment]
Closing due to inactivity. Feel free to reopen if you are still having trouble.
