### ISSUE TITLE
Color error

### ISSUE THREAD

**Issue by andim27** [jonbhanson/flutter_native_splash#638]
I use this color: #E4F6CFCA and this: #042a49
And I have an error:
```
Unhandled exception:
Exception: Invalid color value
#0      parseColor (package:flutter_native_splash/cli_commands.dart:401:3)
#1      _createSplashByConfig (package:flutter_native_splash/cli_commands.dart:81:25)
#2      createSplash (package:flutter_native_splash/cli_commands.dart:43:3)
```
p.s.  flutter_native_splash: ^2.3.8

**Comment by jonbhanson** [comment]
Please attach your config.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.
