### ISSUE TITLE
flutter_native_splash plugin fails to build

### ISSUE THREAD

**Issue by ErfanManafi** [jonbhanson/flutter_native_splash#717]
**Attention**: I have checked the notes on Android 12 and my issue does not seem related.

The flutter_native_splash plugin fails to build when using the latest Android SDK (version 35.0.0). It seems the plugin is trying to access older build tools that are not present in the current SDK.

Flutter 3.22.2 • channel stable

**Comment by TalebRafiepour** [comment]
failed to build on Android:

flutter_native_splash: ^2.4.1

Flutter 3.22.2 • channel stable

log:
```
A problem occurred configuring project ':flutter_native_splash'.
> Could not resolve all files for configuration ':flutter_native_splash:classpath'.
   > Could not find gradle-7.1.2.jar (com.android.tools.build:gradle:7.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.1.2/gradle-7.1.2.jar
   > Could not find builder-7.1.2.jar (com.android.tools.build:builder:7.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/7.1.2/builder-7.1.2.jar
   > Could not find sdk-common-30.1.2.jar (com.android.tools:sdk-common:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/30.1.2/sdk-common-30.1.2.jar
   > Could not find sdklib-30.1.2.jar (com.android.tools:sdklib:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/30.1.2/sdklib-30.1.2.jar
   > Could not find repository-30.1.2.jar (com.android.tools:repository:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/30.1.2/repository-30.1.2.jar
   > Could not find ddmlib-30.1.2.jar (com.android.tools.ddms:ddmlib:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/30.1.2/ddmlib-30.1.2.jar
   > Could not find aaptcompiler-7.1.2.jar (com.android.tools.build:aaptcompiler:7.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/aaptcompiler/7.1.2/aaptcompiler-7.1.2.jar
   > Could not find aapt2-proto-7.1.2-7984345.jar (com.android.tools.build:aapt2-proto:7.1.2-7984345).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/7.1.2-7984345/aapt2-proto-7.1.2-7984345.jar
   > Could not find crash-30.1.2.jar (com.android.tools.analytics-library:crash:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/30.1.2/crash-30.1.2.jar
   > Could not find tracker-30.1.2.jar (com.android.tools.analytics-library:tracker:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/30.1.2/tracker-30.1.2.jar
   > Could not find shared-30.1.2.jar (com.android.tools.analytics-library:shared:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/30.1.2/shared-30.1.2.jar
   > Could not find databinding-compiler-common-7.1.2.jar (androidx.databinding:databinding-compiler-common:7.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/7.1.2/databinding-compiler-common-7.1.2.jar
   > Could not find databinding-common-7.1.2.jar (androidx.databinding:databinding-common:7.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/7.1.2/databinding-common-7.1.2.jar
   > Could not find baseLibrary-7.1.2.jar (com.android.databinding:baseLibrary:7.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/7.1.2/baseLibrary-7.1.2.jar
   > Could not find layoutlib-api-30.1.2.jar (com.android.tools.layoutlib:layoutlib-api:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/30.1.2/layoutlib-api-30.1.2.jar
   > Could not find android-device-provider-ddmlib-proto-30.1.2.jar (com.android.tools.utp:android-device-provider-ddmlib-proto:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-device-provider-ddmlib-proto/30.1.2/android-device-provider-ddmlib-proto-30.1.2.jar
   > Could not find android-device-provider-gradle-proto-30.1.2.jar (com.android.tools.utp:android-device-provider-gradle-proto:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-device-provider-gradle-proto/30.1.2/android-device-provider-gradle-proto-30.1.2.jar
   > Could not find android-test-plugin-host-additional-test-output-proto-30.1.2.jar (com.android.tools.utp:android-test-plugin-host-additional-test-output-proto:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-test-plugin-host-additional-test-output-proto/30.1.2/android-test-plugin-host-additional-test-output-proto-30.1.2.jar
   > Could not find android-test-plugin-host-coverage-proto-30.1.2.jar (com.android.tools.utp:android-test-plugin-host-coverage-proto:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-test-plugin-host-coverage-proto/30.1.2/android-test-plugin-host-coverage-proto-30.1.2.jar
   > Could not find android-test-plugin-host-retention-proto-30.1.2.jar (com.android.tools.utp:android-test-plugin-host-retention-proto:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-test-plugin-host-retention-proto/30.1.2/android-test-plugin-host-retention-proto-30.1.2.jar
   > Could not find android-test-plugin-result-listener-gradle-proto-30.1.2.jar (com.android.tools.utp:android-test-plugin-result-listener-gradle-proto:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-test-plugin-result-listener-gradle-proto/30.1.2/android-test-plugin-result-listener-gradle-proto-30.1.2.jar
   > Could not find builder-model-7.1.2.jar (com.android.tools.build:builder-model:7.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/7.1.2/builder-model-7.1.2.jar
   > Could not find dvlib-30.1.2.jar (com.android.tools:dvlib:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/30.1.2/dvlib-30.1.2.jar
   > Could not find common-30.1.2.jar (com.android.tools:common:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/common/30.1.2/common-30.1.2.jar
   > Could not find apkzlib-7.1.2.jar (com.android.tools.build:apkzlib:7.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/7.1.2/apkzlib-7.1.2.jar
   > Could not find protos-30.1.2.jar (com.android.tools.analytics-library:protos:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/30.1.2/protos-30.1.2.jar
   > Could not find signflinger-7.1.2.jar (com.android:signflinger:7.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/signflinger/7.1.2/signflinger-7.1.2.jar
   > Could not find zipflinger-7.1.2.jar (com.android:zipflinger:7.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/zipflinger/7.1.2/zipflinger-7.1.2.jar
   > Could not find annotations-30.1.2.jar (com.android.tools:annotations:30.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/30.1.2/annotations-30.1.2.jar
   > Could not find apksig-7.1.2.jar (com.android.tools.build:apksig:7.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/7.1.2/apksig-7.1.2.jar
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':flutter_native_splash' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':flutter_native_splash' of type org.gradle.api.Project.
```

**Comment by TalebRafiepour** [comment]
Also another error when running following command:
flutter clean
flutter pub get
dart run flutter_native_splash:create --path=native_splash.yaml 

error log: 
```
Building package executable... 
Built flutter_native_splash:create.
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
Unhandled exception:
XmlParserException: ">" expected at 3:24
#0      XmlEventIterator.moveNext (package:xml/src/xml_events/iterator.dart:43:9)
#1      Iterable.forEach (dart:core/iterable.dart:347:23)
#2      XmlNodeDecoder.convertIterable (package:xml/src/xml_events/converters/node_decoder.dart:53:12)
#3      new XmlDocument.parse (package:xml/src/xml/nodes/document.dart:34:47)
#4      _applyOrientation (package:flutter_native_splash/android.dart:540:40)
#5      _createAndroidSplash (package:flutter_native_splash/android.dart:211:3)
#6      _createSplashByConfig (package:flutter_native_splash/cli_commands.dart:160:7)
#7      createSplash (package:flutter_native_splash/cli_commands.dart:43:3)
#8      main (file:///Users/taleb/.pub-cache/hosted/pub.dev/flutter_native_splash-2.4.1/bin/create.dart:31:5)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by jonbhanson** [comment]
@ErfanManafi I have tested the package with API 35 and Flutter 3.22.2, and did not run into any problems.  Please post the error messages that you are encountering and advise how to replicate or post a minimal code example that demonstrates the problem.

@TalebRafiepour judging from the error code, it looks like you have an error in your `values-night/styles.xml` file.

**Comment by jonbhanson** [comment]
@TalebRafiepour glad to hear it is resolved for you.  @ErfanManafi closed due to inactivity.  Feel free to reopen if you are still having trouble.

**Comment by ErfanManafi** [comment]
@jonbhanson solved, Thank you for your attention.
