### ISSUE TITLE
Not able to find 'LaunchImage' image tag in LaunchScreen.storyboard.

### ISSUE THREAD

**Issue by corymalcolmtaylor** [jonbhanson/flutter_native_splash#98]
Just  a note for others who might get this error: I started getting this error recently:

```
 flutter pub pub run flutter_native_splash:create 
[Android] Creating splash images
[Android] Updating launch_background.xml with splash image path
[Android] Updating colors.xml with color for splash screen background
[iOS] Creating splash images
[iOS] Updating LaunchScreen.storyboard with width, height and color
Unhandled exception:
*** ERROR [flutter_native_splash] ***
LaunchScreenStoryboardModified
Not able to find 'LaunchImage' image tag in LaunchScreen.storyboard. Image for splash screen not updated. Did you modify your default LaunchScreen.storyboard file?
#0      _updateLaunchScreenStoryboard (package:flutter_native_splash/ios.dart:142:7)
<asynchronous suspension>
#1      _applyLaunchScreenStoryboard (package:flutter_native_splash/ios.dart:78:12)
#2      createSplash (package:flutter_native_splash/ios.dart:29:9)
<asynchronous suspension>
#3      createSplash (package:flutter_native_splash/flutter_native_splash.dart:24:11)
<asynchronous suspension>
#4      main (file:///Volumes/macex/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-0.1.9/bin/create.dart:5:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

The fix was to add this `<resources> <image name="LaunchImage" /> </resources>`  after the `<scenes>...</scenes>` tag in the  .../ios/Runner/Base.lproj/LaunchScreen.storyboard file, and then to rerun the create command.  Maybe running flutter clean helped too.

PS: Is this going to get maintained?

PPS:  Then to get the image to show up I still needed to open Xcode and select the Launch Screen File and but also add more tags tot he storyboard view tag file.  I ended up with a view tag the looks like this:
```<view key="view" contentMode="scaleToFill" id="Ze5-6b-2t3">
    <rect key="frame" x="0.0" y="0.0" width="414" height="896"/>
    <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
    <subviews>
        <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="251" verticalHuggingPriority="251" image="LaunchImage" highlightedImage="LaunchImage" id="vSu-qP-VOK">
           <rect key="frame" x="57" y="275" width="300" height="287"/>
           <autoresizingMask key="autoresizingMask" flexibleMinX="YES" widthSizable="YES" flexibleMaxX="YES" flexibleMinY="YES" heightSizable="YES" flexibleMaxY="YES"/>
       </imageView>
    </subviews>
    <color key="backgroundColor" red="0.0" green="0.0" blue="0.0" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>
    <constraints>
        <constraint firstItem="vSu-qP-VOK" firstAttribute="centerX" secondItem="Ze5-6b-2t3" secondAttribute="centerX" priority="999" id="Qas-GG-qgv"/>
       <constraint firstItem="vSu-qP-VOK" firstAttribute="centerY" secondItem="Ze5-6b-2t3" secondAttribute="centerY" priority="999" id="d3g-lJ-eOJ"/>
    </constraints>
    </view>
```

**Comment by jonbhanson** [comment]
At this time, the package works under the assumption that the default Flutter splash image has not been modified.  It sounds like LaunchScreen.storyboard was modified, which is why you received the error.

**Comment by glonaldo70** [comment]
what we have to do in that situation?

**Comment by jonbhanson** [comment]
You could create a new Flutter project, and copy the LaunchScreen.storyboard from the new project and overwrite the same file in your existing project.
